name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        Plan: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    - uses: actions/checkout@v4
    - name: Repeater compile
      run: g++ -O3 intentionRepeater.cpp
    - name: Make swap
      run: (sudo fallocate -l 14G /swapfile) && (sudo chmod 600 /swapfile) && (sudo mkswap /swapfile) && (sudo swapon /swapfile)
    - name: Repeater run
      run: ./a.out --dur 06:00:00 --imem 20 --intent "INTENTIONS.txt"

          echo Add other actions to build,
          echo test, and deploy your project.
